tunnel: 9971c2bf-82d8-4113-ae08-aed47afbd237
credentials-file: /home/alex/.cloudflared/9971c2bf-82d8-4113-ae08-aed47afbd237.json

ingress:
  - hostname: api.alexako.com
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      # Allow all headers to pass through
      httpHostHeader: api.alexako.com
  - service: http_status:404
